# -*- coding: utf-8 -*-
"""Cópia de Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vVNnFN7bPkrtm5GasrMdNs4SKo_CVdV3
"""

import pandas as pd

# --- Passo 1: Defina a URL da sua Planilha Google (já adaptada) ---
google_sheet_url = 'https://docs.google.com/spreadsheets/d/1SQiuZP_ON7dy539dXaMJv9VW3SgLLqbbgAphAqQmB0w/export?format=csv&gid=48792188'

try:
    # --- Passo 2: Ler a planilha diretamente para um DataFrame ---
    # O pandas consegue ler um CSV diretamente de uma URL
    df = pd.read_csv(google_sheet_url)
    print("Dados carregados com sucesso da Planilha Google!")

    # --- Verificação Final ---
    print("\nAs 5 primeiras linhas do seu DataFrame:")
    # No Kaggle/Jupyter, display() é mais elegante que print() para DataFrames
    display(df.head())

except Exception as e:
    print(f"Ocorreu um erro ao tentar ler a planilha: {e}")
    print("\nPossíveis causas:")
    print("1. A URL está incorreta.")
    print("2. A planilha não está compartilhada como 'Qualquer pessoa com o link pode ver'.")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np

# Separa as features (X) do alvo (y)
X = df.drop(['Nome', 'Carteirinha', 'Reinternado_30_Dias', 'ProbabilidadeRisco'], axis=1)
y = df['Reinternado_30_Dias']

# Identifica colunas numéricas e categóricas
numeric_features = X.select_dtypes(include=np.number).columns
categorical_features = X.select_dtypes(include='object').columns

# Cria o pipeline de pré-processamento
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)])


# Divide os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Dados preparados e divididos para o treinamento.")

from sklearn.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.utils.class_weight import compute_sample_weight

# Cria o pipeline final que junta o pré-processador com o modelo
model_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                                 ('classifier', GradientBoostingClassifier(n_estimators=100, random_state=42))])

# --- CALCULAR OS PESOS ---
# Isso vai dar um peso maior para a classe minoritária (Reinternado_30_Dias = True)
sample_weights = compute_sample_weight(
    class_weight='balanced',
    y=y_train
)

# Treina o modelo com os dados de treino
print("Iniciando o treinamento do modelo...")
model_pipeline.fit(X_train, y_train, classifier__sample_weight=sample_weights)
print("Treinamento concluído!")

from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

print("\\n--- AVALIAÇÃO DO MODELO ---")
y_pred = model_pipeline.predict(X_test)
y_pred_proba = model_pipeline.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print(f"AUC-ROC Score: {roc_auc_score(y_test, y_pred_proba):.4f}")

# Matriz de Confusão
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Matriz de Confusão')
plt.ylabel('Verdadeiro')
plt.xlabel('Previsão')
plt.show()

# Usar o modelo para prever a probabilidade de risco para TODOS os pacientes
full_data_predictions = model_pipeline.predict_proba(X)[:, 1]

# Criar um DataFrame com os resultados
df_resultados = pd.DataFrame({
    'Nome': df['Nome'],
    'Genero': df['Genero'],
    'Idade': df['Idade'],
    'Dependentes' : df['Dependentes'],
    'Carteirinha': df['Carteirinha'],
    'ScoreRisco_Preditivo': full_data_predictions
})

# Ordenar pela maior probabilidade de risco
df_resultados = df_resultados.sort_values(by='ScoreRisco_Preditivo', ascending=False)

# Salvar o resultado em um arquivo CSV
df_resultados.to_csv('previsoes_finais.csv', index=False)

print("\\nArquivo 'previsoes_finais.csv' gerado com sucesso!")
print("As 5 maiores prioridades de atendimento são:")
display(df_resultados.head())

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# --- Seu código existente ---
# Pega as probabilidades em vez da previsão final
y_pred_proba = model_pipeline.predict_proba(X_test)[:, 1]

# --- NOVA LINHA: DEFINIR UM NOVO LIMIAR ---
novo_limiar = 0.30

# Faz a previsão com base no novo limiar
y_pred_novo_limiar = (y_pred_proba >= novo_limiar).astype(int)

print(f"\\n--- AVALIAÇÃO COM LIMIAR DE {novo_limiar*100}% ---")
print(classification_report(y_test, y_pred_novo_limiar))


# --- CÓDIGO ADICIONADO PARA GERAR A MATRIZ DE CONFUSÃO ---

print("\\n--- MATRIZ DE CONFUSÃO COM NOVO LIMIAR ---")

# Calcula a matriz de confusão
cm = confusion_matrix(y_test, y_pred_novo_limiar)

# Desenha a matriz de forma visual
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Não Reinternou', 'Reinternou'],
            yticklabels=['Não Reinternou', 'Reinternou'])
plt.title(f'Matriz de Confusão (Limiar de {novo_limiar*100}%)')
plt.ylabel('Verdadeiro')
plt.xlabel('Previsão')
plt.show()

!pip install gspread google-auth

from google.colab import auth
from google.auth import default
import gspread
import pandas as pd

# Authenticate to Google
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# --- Passo 1: Defina o nome da sua Planilha Google e a aba ---
# Substitua por seus valores
spreadsheet_name = 'ResultadosUnimed' # Ex: 'Minha Planilha de Pacientes'
worksheet_name = 'PacientesAltoRisco' # Ex: 'Pacientes Alto Risco'

# --- Passo 2: Filtrar pacientes com Score de Risco Preditivo >= 0.65 ---
score_minimo = 0.65
df_alto_risco = df_resultados[df_resultados['ScoreRisco_Preditivo'] >= score_minimo].copy()

# --- Passo 3: Adicionar o novo campo booleano 'Visitado' ---
# O valor inicial é False, indicando que a visita ainda não foi realizada
df_alto_risco['Visitado'] = False

print("Pacientes com Score de Risco >= 0.65 e Coluna 'Visitado':")
display(df_alto_risco)


try:
    # --- Passo 4: Abrir a planilha e selecionar a aba ---
    sh = gc.open(spreadsheet_name)
    ws = sh.worksheet(worksheet_name)

    # --- Passo 5: Limpar o conteúdo existente na aba (opcional, mas recomendado) ---
    ws.clear()

    # --- Passo 6: Escrever os dados do DataFrame para a planilha ---
    # Converter o DataFrame para uma lista de listas (formato que gspread entende)
    data_to_write = [df_alto_risco.columns.tolist()] + df_alto_risco.values.tolist()

    # Escrever os dados na planilha
    ws.update(data_to_write)

    print(f"\nDados exportados com sucesso para a planilha '{spreadsheet_name}' na aba '{worksheet_name}'!")

except Exception as e:
    print(f"Ocorreu um erro ao tentar escrever na planilha: {e}")
    print("\nPossíveis causas:")
    print("1. O nome da planilha ou da aba está incorreto.")
    print("2. Você não tem permissão de escrita na planilha.")
    print("3. A autenticação não foi bem-sucedida.")